version: '3.6'

services:
  frontend:
    build: 
      dockerfile: docker/Dockerfile
      context: .
    image: frontend:latest
    volumes:
      - ./configs/runtimeConfig.js:/app/src/runtimeConfig.js
    ports:
      - 3000:3000
    environment: 
      - BROWSER=None
      - CI=true
    command: npm start